[package]
name = "backend"
version = "0.1.0"
authors = ["Keisuke Toyota <hm.pudding0715@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.10"
actix-web = "3"
sqlx = { version = "0.3", features = [ "mysql" ] }
anyhow = "1.0"
dotenv = "0.15"
futures = "0.3"
listenfd = "0.3"